version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/app
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: sudo apt-get -y -qq install awscli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: npm run lint
      - run: npm run test

      # Deploy
      - deploy:
          name: Deploy to s3
          command: |
            npm run build \
            aws s3 sync build/ s3://unite-app/
