// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var SemanticUiReact = require("semantic-ui-react");

function make(placeholder, selection, value, onChange, options, children) {
  return ReasonReact.wrapJsForReason(SemanticUiReact.Dropdown, {
              placeholder: Js_null_undefined.fromOption(placeholder),
              selection: Js_null_undefined.fromOption(selection),
              value: Js_null_undefined.fromOption(value),
              onChange: onChange,
              options: options
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
