// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Menu$Unite = require("./Menu.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Dropdown$Unite = require("./Dropdown.bs.js");

var component = ReasonReact.statelessComponent("UserSelect");

function make(selectedUser, onSelect, userOptions, _) {
  var handleChange = function (_, _$1) {
    return Curry._1(onSelect, /* () */0);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, Menu$Unite.make(/* Some */[/* true */1], /* array */[ReasonReact.element(/* None */0, /* None */0, Dropdown$Unite.make(/* Some */["Select your user"], /* Some */[/* true */1], /* Some */[selectedUser[/* value */1]], /* Some */[Curry._1(self[/* handle */0], handleChange)], /* Some */[userOptions], /* array */[]))]));
    });
  return newrecord;
}

function fromJsProps(props) {
  return make(props.selectedUser, props.onSelect, props.userOptions, /* array */[]);
}

var $$default = ReasonReact.wrapReasonForJs(component, fromJsProps);

exports.component = component;
exports.make = make;
exports.fromJsProps = fromJsProps;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
